name: Build and deploy Doxygen documentation

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    # Build Doxygen documentation
    # mattnotmitt/doxygen-action
    # https://github.com/marketplace/actions/doxygen-action

    - uses: mattnotmitt/doxygen-action@v1.9.5
      with :
        doxyfile-path: ./Doxyfile

    # Deploy Doxygen documentation
    # peaceiris/actions-gh-pages
    # https://github.com/peaceiris/actions-gh-pages
    - name : Deploy
    - use : peaceiris/action-gh-pages@v3
      with : 
        github_token : ${{ secrets.PERSONAL_TOKEN }}
        publish_dir : ./public


